name: flutter_satispay
description: Flutter package to handle Satispay payments.

version: 0.0.1

homepage: https://github.com/zippa-pizza/flutter_satispay
repository: https://github.com/zippa-pizza/flutter_satispay

platforms:
  android:
  ios:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSansPro-Regular.ttf
          weight: 400
